version: "3"
services:

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9999:4567"
      depends_on:
        - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "9999:4567"
    image: softy-pinko-back-end:task4