version: "3"
services:

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      image: softy-pinko-front-end:task4
      ports:
        - "9999:4567"
      depends_on:
        - front-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
      image: softy-pinko-back-end:task4
      ports:
        - "9999:4567"
      depends_on:
        - back-end